
version: '3.8'

services:
  deepdns:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VERSION: ${VERSION:-1.0}
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
    image: deepdns:${VERSION:-1.0}
    container_name: deepdns-scanner
    volumes:
      - ./output:/app/output:rw
      - ./config:/app/config:ro
    security_opt:
      - no-new-privileges
    cpu_shares: 1024
    mem_limit: 2g
    memswap_limit: 2g
    network_mode: host
    restart: "no"